substitutions:
  systemName: bthome-1

esphome:
  name: $systemName

esp32:
  board: esp32dev
  # wemos_d1_mini32

external_components:
  - source: github://ahsan-kaukab/esphome_btreceiver
    refresh: 1min

logger:
  level: debug
  # level: info

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80
  ota: false

esp32_ble_tracker:
  scan_parameters:
    active: false

bthome_ble_receiver:
  dump: unmatched
  devices:
    - mac_address: 11:22:33:44:55:66
      name_prefix: BTHome Living Room
    - mac_address: AA:BB:CC:DD:EE:FF
      name_prefix: BTHome Garage
    - mac_address: 22:33:44:55:66:77
      dump: all

sensor:
  - platform: bthome_ble_receiver
    mac_address: 11:22:33:44:55:66
    sensors:
      - measurement_type: temperature
        name: Temperature
      - measurement_type: humidity
        name: Humidity
      - measurement_type: packet_id
        name: PacketId

  - platform: bthome_ble_receiver
    mac_address: AA:BB:CC:DD:EE:FF
    sensors:
      - measurement_type: temperature
        name: Temperature
      - measurement_type: 0x02
        name: Temperature 2
        accuracy_decimals: 2
        unit_of_measurement: °C
      - measurement_type: 0x02
        name: Temperature 3
      - measurement_type: count_4
        name: Count

  - platform: bthome_ble_receiver
    mac_address: 22:33:44:55:66:77
    sensors:
      - measurement_type: temperature
        name: BTHome Workshop Temperature

binary_sensor:
  - platform: bthome_ble_receiver
    mac_address: AA:BB:CC:DD:EE:FF
    sensors:
      - measurement_type: opening
        name: Garage