esphome:
  name: myespdevice  # Change to avoid underscore warning
  platform: ESP32
  board: esp32dev

external_components:
  - source: "/home/flinux/Desktop/esphome_component_bthome-master/components"
  
wifi:
  ssid: "your_ssid"
  password: "your_password"

mqtt:
  broker: "your_mqtt_broker"
  username: "your_username"
  password: "your_password"

logger:
  level: DEBUG

ota:

mqtt_wl_rr:
  id: my_mqtt_wl_rr
  component_name: "mqtt_wl_rr"
  mqtt_topic: "your_device_prefix/mqtt_wl_rr/config"
  mac_address: "00:11:22:33:44:55"
