substitutions:
  systemName: bthome-1

esphome:
  name: $systemName

esp32:
  board: esp32dev
  
  # wemos_d1_mini32

# globals: 
#   - id: a 
#     type: int 
#     restore_value: yes 
#     initial_value: '0'
  
preferences:
 flash_write_interval: 1s
 #restore_from_flash: "true"

external_components:
  #- source: "github://ahsan-kaukab/esphome_compoennt_new"
  #- source: github://martgras/esphome@nvs-fix
  - source: "/home/flinux/Desktop/esphome_component_bthome-master/components"
  #- source: "github://martgras/esphome@nvs-fix"
  #components: [ esp32]

logger:
  level: info

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker_n
  username: !secret mqtt_username_n
  password: !secret mqtt_password_n
  port: 1883

web_server:
  port: 80
  ota: false

esp32_ble_tracker:
  scan_parameters:
    active: false

bthome_ble_receiver:
  #dump: unmatched
  devices:
    - #mqtt_topic : Hello
      #mac_address: AA:BB:CC:DD:EE:FF
      mac_address: 2048
      name_prefix: BTHome Living Room
    - #mqtt_topic : Hello
      #mac_address: AA:BB:CC:DD:EE:FF
      mac_address: 2048
      name_prefix: BTHome Garage
    - #mqtt_topic : Hello
      #mac_address: AA:BB:CC:DD:EE:FF
      mac_address: 2048
      #dump: all

sensor:
  - platform: bthome_ble_receiver
    #mqtt_topic : Hello
    #mac_address: AA:BB:CC:DD:EE:FF
    mac_address: 2048
    sensors:
      - measurement_type: temperature
        name: Temperature
      - measurement_type: humidity
        name: Humidity
      - measurement_type: packet_id
        name: PacketId

  - platform: bthome_ble_receiver
    #mqtt_topic : Hello
    #mac_address: AA:BB:CC:DD:EE:FF
    mac_address: 2048
    sensors:
      - measurement_type: temperature
        name: Temperature
      - measurement_type: 0x02
        name: Temperature 2
        accuracy_decimals: 2
        unit_of_measurement: °C
      - measurement_type: 0x02
        name: Temperature 3
      - measurement_type: count_4
        name: Count

  - platform: bthome_ble_receiver
    #mqtt_topic : Hello
    #mac_address: AA:BB:CC:DD:EE:FF
    mac_address: 2048
    sensors:
      - measurement_type: temperature
        name: BTHome Workshop Temperature

binary_sensor:
  - platform: bthome_ble_receiver
    #optimistic: true
    #restore_state: true
    #mqtt_topic : Hello
    #mac_address: AA:BB:CC:DD:EE:FF
    mac_address: 2048
    sensors:
      - measurement_type: opening
        name: Garage
        #restore_mode: RESTORE_DEFAULT_ON
        # optimistic: 'true'
        # restore_state: 'true'
        # restore_mode: RESTORE_DEFAULT_ON
